import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'
import Dummy from './components/dummy'

export default function Home() {
  return (
    <div className={styles.container}>
      <Dummy/>
      <style jsx >
        {`
            .mySpan{
              color :red;
            }
        `}
      </style>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="next js, hunting coder blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <Link href="/"><li>Home</li></Link>
          <Link href="/about"><li>About</li></Link>
          <Link href="/blog"><li>Blog</li></Link>
          <Link href="/contact"><li>Contact</li></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='mySpan dummy'>Hunting coder</span>        
        </h1>

        <p className={styles.description}>
          A blog for Hunting coders by coders
        </p>
        {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}

        <div className="blogs">
          <h2>Popular blogs</h2>
          <div className="blogItem">
            <h3>How to learn Javascript in 2020?</h3>
            <p>Javascript is a language used for logic in web</p>
          </div>
        </div>
        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn Javascript in 2020?</h3>
            <p>Javascript is a language used for logic in web</p>
          </div>
        </div>
        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn Javascript in 2020?</h3>
            <p>Javascript is a language used for logic in web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
